<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <!--If you are willing to use platform-specific APIs, use conditional compilation.
    See https://docs.avaloniaui.net/docs/guides/platforms/platform-specific-code/dotnet for more details.-->
    <TargetFrameworks>net10.0-windows10.0.19041;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Letra200bSharp.Avalonia\Letra200bSharp.Avalonia.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Update="Icon %281%29.ico" Link="Icon.ico" />
  </ItemGroup>
</Project>
