//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Letra200bSharp.Avalonia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Letra200bSharp.Avalonia.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledgements.
        /// </summary>
        public static string AboutTab_AcknowledgementsHeader {
            get {
                return ResourceManager.GetString("AboutTab_AcknowledgementsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License (MIT).
        /// </summary>
        public static string AboutTab_LicenseLabel {
            get {
                return ResourceManager.GetString("AboutTab_LicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        public static string AboutTab_RepositoryLabel {
            get {
                return ResourceManager.GetString("AboutTab_RepositoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# library and app for printing labels to a Dymo LetraTag 200B over Bluetooth LE..
        /// </summary>
        public static string AboutTab_Tagline {
            get {
                return ResourceManager.GetString("AboutTab_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used libraries.
        /// </summary>
        public static string AboutTab_UsedLibrariesHeader {
            get {
                return ResourceManager.GetString("AboutTab_UsedLibrariesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string AboutTab_VersionFormat {
            get {
                return ResourceManager.GetString("AboutTab_VersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data:.
        /// </summary>
        public static string BarcodeTab_DataLabel {
            get {
                return ResourceManager.GetString("BarcodeTab_DataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. 0123456789.
        /// </summary>
        public static string BarcodeTab_DataPlaceholder {
            get {
                return ResourceManager.GetString("BarcodeTab_DataPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption font:.
        /// </summary>
        public static string BarcodeTab_CaptionFontLabel {
            get {
                return ResourceManager.GetString("BarcodeTab_CaptionFontLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Caption:.
        /// </summary>
        public static string BarcodeTab_CaptionPositionLabel {
            get {
                return ResourceManager.GetString("BarcodeTab_CaptionPositionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Caption size:.
        /// </summary>
        public static string BarcodeTab_CaptionSizeLabel {
            get {
                return ResourceManager.GetString("BarcodeTab_CaptionSizeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No barcode data entered..
        /// </summary>
        public static string BarcodeTab_NoDataEntered {
            get {
                return ResourceManager.GetString("BarcodeTab_NoDataEntered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Symbology:.
        /// </summary>
        public static string BarcodeTab_SymbologyLabel {
            get {
                return ResourceManager.GetString("BarcodeTab_SymbologyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align:.
        /// </summary>
        public static string Common_AlignLabel {
            get {
                return ResourceManager.GetString("Common_AlignLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Concatenate.
        /// </summary>
        public static string Common_Concatenate {
            get {
                return ResourceManager.GetString("Common_Concatenate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add to the Compose tab&apos;s staged elements.
        /// </summary>
        public static string Common_ConcatenateTooltip {
            get {
                return ResourceManager.GetString("Common_ConcatenateTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No cut.
        /// </summary>
        public static string Common_NoCut {
            get {
                return ResourceManager.GetString("Common_NoCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Common_Preview {
            get {
                return ResourceManager.GetString("Common_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Common_Print {
            get {
                return ResourceManager.GetString("Common_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear all.
        /// </summary>
        public static string ComposeTab_ClearAllButton {
            get {
                return ResourceManager.GetString("ComposeTab_ClearAllButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Drag to reorder.
        /// </summary>
        public static string ComposeTab_DragHandleTooltip {
            get {
                return ResourceManager.GetString("ComposeTab_DragHandleTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nothing staged to print yet..
        /// </summary>
        public static string ComposeTab_NoElements {
            get {
                return ResourceManager.GetString("ComposeTab_NoElements", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nothing staged yet - use &quot;Concatenate&quot; on the Image, Text, Barcode, 2D Code, or Draw tab to add elements here..
        /// </summary>
        public static string ComposeTab_NoElementsYet {
            get {
                return ResourceManager.GetString("ComposeTab_NoElementsYet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string ComposeTab_RemoveButton {
            get {
                return ResourceManager.GetString("ComposeTab_RemoveButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string ComposeTab_DuplicateButton {
            get {
                return ResourceManager.GetString("ComposeTab_DuplicateButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert a copy of this element right after it.
        /// </summary>
        public static string ComposeTab_DuplicateTooltip {
            get {
                return ResourceManager.GetString("ComposeTab_DuplicateTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to + Add label.
        /// </summary>
        public static string DinRailTab_AddRowButton {
            get {
                return ResourceManager.GetString("DinRailTab_AddRowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to reorder.
        /// </summary>
        public static string DinRailTab_DragHandleTooltip {
            get {
                return ResourceManager.GetString("DinRailTab_DragHandleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIN modules.
        /// </summary>
        public static string DinRailTab_ModulesColumnHeader {
            get {
                return ResourceManager.GetString("DinRailTab_ModulesColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No text entered..
        /// </summary>
        public static string DinRailTab_NoTextEntered {
            get {
                return ResourceManager.GetString("DinRailTab_NoTextEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this label.
        /// </summary>
        public static string DinRailTab_RemoveRowTooltip {
            get {
                return ResourceManager.GetString("DinRailTab_RemoveRowTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print separators.
        /// </summary>
        public static string DinRailTab_SeparatorsCheckbox {
            get {
                return ResourceManager.GetString("DinRailTab_SeparatorsCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 mm tall · {0:0.#} mm printed ({1} labels).
        /// </summary>
        public static string DinRailTab_SizeNoteFormat {
            get {
                return ResourceManager.GetString("DinRailTab_SizeNoteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizing:.
        /// </summary>
        public static string DinRailTab_SizingLabel {
            get {
                return ResourceManager.GetString("DinRailTab_SizingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string DinRailTab_TextColumnHeader {
            get {
                return ResourceManager.GetString("DinRailTab_TextColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. General, Outlets, Lights.
        /// </summary>
        public static string DinRailTab_TextPlaceholder {
            get {
                return ResourceManager.GetString("DinRailTab_TextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This text needs a lot of shrinking to fit - it will likely print too small to read. Shorten it or add more modules..
        /// </summary>
        public static string DinRailTab_TooSmallWarning {
            get {
                return ResourceManager.GetString("DinRailTab_TooSmallWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0:0.#} total).
        /// </summary>
        public static string DinRailTab_TotalModulesFormat {
            get {
                return ResourceManager.GetString("DinRailTab_TotalModulesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush:.
        /// </summary>
        public static string DrawTab_BrushLabel {
            get {
                return ResourceManager.GetString("DrawTab_BrushLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string DrawTab_ClearButton {
            get {
                return ResourceManager.GetString("DrawTab_ClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing.
        /// </summary>
        public static string DrawTab_DefaultHistoryLabel {
            get {
                return ResourceManager.GetString("DrawTab_DefaultHistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol {0:HH:mm:ss}.
        /// </summary>
        public static string DrawTab_DefaultSymbolNameFormat {
            get {
                return ResourceManager.GetString("DrawTab_DefaultSymbolNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DrawTab_DeleteSymbolButton {
            get {
                return ResourceManager.GetString("DrawTab_DeleteSymbolButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eraser.
        /// </summary>
        public static string DrawTab_EraserTool {
            get {
                return ResourceManager.GetString("DrawTab_EraserTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string DrawTab_LoadSymbolButton {
            get {
                return ResourceManager.GetString("DrawTab_LoadSymbolButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No symbols saved yet - draw something above and use &quot;Save as symbol&quot;..
        /// </summary>
        public static string DrawTab_NoSymbolsYet {
            get {
                return ResourceManager.GetString("DrawTab_NoSymbolsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing drawn yet..
        /// </summary>
        public static string DrawTab_NothingDrawn {
            get {
                return ResourceManager.GetString("DrawTab_NothingDrawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen.
        /// </summary>
        public static string DrawTab_PenTool {
            get {
                return ResourceManager.GetString("DrawTab_PenTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string DrawTab_PrintSymbolButton {
            get {
                return ResourceManager.GetString("DrawTab_PrintSymbolButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as symbol.
        /// </summary>
        public static string DrawTab_SaveAsSymbolButton {
            get {
                return ResourceManager.GetString("DrawTab_SaveAsSymbolButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show grid.
        /// </summary>
        public static string DrawTab_ShowGridCheckbox {
            get {
                return ResourceManager.GetString("DrawTab_ShowGridCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol name:.
        /// </summary>
        public static string DrawTab_SymbolNameLabel {
            get {
                return ResourceManager.GetString("DrawTab_SymbolNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Warning triangle.
        /// </summary>
        public static string DrawTab_SymbolNamePlaceholder {
            get {
                return ResourceManager.GetString("DrawTab_SymbolNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol saved..
        /// </summary>
        public static string DrawTab_SymbolSaved {
            get {
                return ResourceManager.GetString("DrawTab_SymbolSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved symbols.
        /// </summary>
        public static string DrawTab_SymbolsHeader {
            get {
                return ResourceManager.GetString("DrawTab_SymbolsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool:.
        /// </summary>
        public static string DrawTab_ToolLabel {
            get {
                return ResourceManager.GetString("DrawTab_ToolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string DrawTab_UndoButton {
            get {
                return ResourceManager.GetString("DrawTab_UndoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width (dots):.
        /// </summary>
        public static string DrawTab_WidthLabel {
            get {
                return ResourceManager.GetString("DrawTab_WidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom:.
        /// </summary>
        public static string DrawTab_ZoomLabel {
            get {
                return ResourceManager.GetString("DrawTab_ZoomLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string HistoryTab_DeleteButton {
            get {
                return ResourceManager.GetString("HistoryTab_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No prints yet..
        /// </summary>
        public static string HistoryTab_NoPrintsYet {
            get {
                return ResourceManager.GetString("HistoryTab_NoPrintsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprint.
        /// </summary>
        public static string HistoryTab_ReprintButton {
            get {
                return ResourceManager.GetString("HistoryTab_ReprintButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to · saved, not printed.
        /// </summary>
        public static string HistoryTab_SavedBadge {
            get {
                return ResourceManager.GetString("HistoryTab_SavedBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string ImageTab_BrowseButton {
            get {
                return ResourceManager.GetString("ImageTab_BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ImageTab_DefaultHistoryLabel {
            get {
                return ResourceManager.GetString("ImageTab_DefaultHistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image:.
        /// </summary>
        public static string ImageTab_ImageLabel {
            get {
                return ResourceManager.GetString("ImageTab_ImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected.
        /// </summary>
        public static string ImageTab_NoFileSelectedPlaceholder {
            get {
                return ResourceManager.GetString("ImageTab_NoFileSelectedPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image file selected..
        /// </summary>
        public static string ImageTab_NoImageSelected {
            get {
                return ResourceManager.GetString("ImageTab_NoImageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-rendered.
        /// </summary>
        public static string ImageTab_PreRenderedCheckbox {
            get {
                return ResourceManager.GetString("ImageTab_PreRenderedCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainView_AboutTabHeader {
            get {
                return ResourceManager.GetString("MainView_AboutTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string MainView_BarcodeTabHeader {
            get {
                return ResourceManager.GetString("MainView_BarcodeTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices:.
        /// </summary>
        public static string MainView_DevicesLabel {
            get {
                return ResourceManager.GetString("MainView_DevicesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose.
        /// </summary>
        public static string MainView_ComposeTabHeader {
            get {
                return ResourceManager.GetString("MainView_ComposeTabHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DIN Rail.
        /// </summary>
        public static string MainView_DinRailTabHeader {
            get {
                return ResourceManager.GetString("MainView_DinRailTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        public static string MainView_DrawTabHeader {
            get {
                return ResourceManager.GetString("MainView_DrawTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string MainView_HistoryTabHeader {
            get {
                return ResourceManager.GetString("MainView_HistoryTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string MainView_ImageTabHeader {
            get {
                return ResourceManager.GetString("MainView_ImageTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dymo LetraTag 200B not found..
        /// </summary>
        public static string MainView_NoPrinterFound {
            get {
                return ResourceManager.GetString("MainView_NoPrinterFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D Code.
        /// </summary>
        public static string MainView_QrTabHeader {
            get {
                return ResourceManager.GetString("MainView_QrTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string MainView_RefreshButton {
            get {
                return ResourceManager.GetString("MainView_RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No prints yet..
        /// </summary>
        public static string MainView_StatsPanelNoDataYet {
            get {
                return ResourceManager.GetString("MainView_StatsPanelNoDataYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats for nerds.
        /// </summary>
        public static string MainView_StatsToggleButtonTooltip {
            get {
                return ResourceManager.GetString("MainView_StatsToggleButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string MainView_TextTabHeader {
            get {
                return ResourceManager.GetString("MainView_TextTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Studio 200B.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data:.
        /// </summary>
        public static string QrTab_DataLabel {
            get {
                return ResourceManager.GetString("QrTab_DataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. https://example.com/  or  RACK-A17-BIN-04.
        /// </summary>
        public static string QrTab_DataPlaceholder {
            get {
                return ResourceManager.GetString("QrTab_DataPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At ~0.16 mm per module this code is at or below the practical limit for phone-camera scanning and is vulnerable to thermal dot gain. Prefer rMQR or Micro QR, or shorten the data..
        /// </summary>
        public static string QrTab_MayNotScanWarning {
            get {
                return ResourceManager.GetString("QrTab_MayNotScanWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No 2D code data entered..
        /// </summary>
        public static string QrTab_NoDataEntered {
            get {
                return ResourceManager.GetString("QrTab_NoDataEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  ·  {1}×{2} dots/module  ·  ~{3:0.00} mm.
        /// </summary>
        public static string QrTab_SymbolInfoFormat {
            get {
                return ResourceManager.GetString("QrTab_SymbolInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbology:.
        /// </summary>
        public static string QrTab_SymbologyLabel {
            get {
                return ResourceManager.GetString("QrTab_SymbologyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to composition..
        /// </summary>
        public static string Status_AddedToComposition {
            get {
                return ResourceManager.GetString("Status_AddedToComposition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No device selected..
        /// </summary>
        public static string Status_NoDeviceSelected {
            get {
                return ResourceManager.GetString("Status_NoDeviceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved to history..
        /// </summary>
        public static string Status_SavedToHistory {
            get {
                return ResourceManager.GetString("Status_SavedToHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate preview: {0}.
        /// </summary>
        public static string Status_UnableToGeneratePreview {
            get {
                return ResourceManager.GetString("Status_UnableToGeneratePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box:.
        /// </summary>
        public static string TextTab_BoxLabel {
            get {
                return ResourceManager.GetString("TextTab_BoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font:.
        /// </summary>
        public static string TextTab_FontLabel {
            get {
                return ResourceManager.GetString("TextTab_FontLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string TextTab_HeightLabel {
            get {
                return ResourceManager.GetString("TextTab_HeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text:.
        /// </summary>
        public static string TextTab_Line1LabelSingle {
            get {
                return ResourceManager.GetString("TextTab_Line1LabelSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Line 1:.
        /// </summary>
        public static string TextTab_Line1LabelWithLine2 {
            get {
                return ResourceManager.GetString("TextTab_Line1LabelWithLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Line 2:.
        /// </summary>
        public static string TextTab_Line2Label {
            get {
                return ResourceManager.GetString("TextTab_Line2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No text entered..
        /// </summary>
        public static string TextTab_NoTextEntered {
            get {
                return ResourceManager.GetString("TextTab_NoTextEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style:.
        /// </summary>
        public static string TextTab_StyleLabel {
            get {
                return ResourceManager.GetString("TextTab_StyleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL UPPERCASE.
        /// </summary>
        public static string TextTab_UppercaseCheckbox {
            get {
                return ResourceManager.GetString("TextTab_UppercaseCheckbox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string TextTab_BoldCheckbox {
            get {
                return ResourceManager.GetString("TextTab_BoldCheckbox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string TextTab_ItalicCheckbox {
            get {
                return ResourceManager.GetString("TextTab_ItalicCheckbox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string TextTab_UnderlineCheckbox {
            get {
                return ResourceManager.GetString("TextTab_UnderlineCheckbox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Strikethrough.
        /// </summary>
        public static string TextTab_StrikethroughCheckbox {
            get {
                return ResourceManager.GetString("TextTab_StrikethroughCheckbox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Letter spacing:.
        /// </summary>
        public static string TextTab_LetterSpacingLabel {
            get {
                return ResourceManager.GetString("TextTab_LetterSpacingLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Frame margin (T/B/L/R):.
        /// </summary>
        public static string TextTab_FrameSpacingLabel {
            get {
                return ResourceManager.GetString("TextTab_FrameSpacingLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        public static string TextTab_WidthLabel {
            get {
                return ResourceManager.GetString("TextTab_WidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Toast_ErrorTitle {
            get {
                return ResourceManager.GetString("Toast_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Toast_SuccessTitle {
            get {
                return ResourceManager.GetString("Toast_SuccessTitle", resourceCulture);
            }
        }
    }
}
