//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Letra200bSharp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Letra200bSharp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing was cancelled..
        /// </summary>
        public static string PrintResult_StatusCancelled {
            get {
                return ResourceManager.GetString("PrintResult_StatusCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing completed..
        /// </summary>
        public static string PrintResult_StatusCompleted {
            get {
                return ResourceManager.GetString("PrintResult_StatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing completed (the printer can report this even when it didn&apos;t actually print, e.g. lid open or no cassette)..
        /// </summary>
        public static string PrintResult_StatusCompletedMaybe {
            get {
                return ResourceManager.GetString("PrintResult_StatusCompletedMaybe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing completed, but the battery is low - it may not print again with the same batteries..
        /// </summary>
        public static string PrintResult_StatusLowBatteryCompleted {
            get {
                return ResourceManager.GetString("PrintResult_StatusLowBatteryCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing failed because the battery is low..
        /// </summary>
        public static string PrintResult_StatusLowBatteryFailed {
            get {
                return ResourceManager.GetString("PrintResult_StatusLowBatteryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing failed because no cassette was inserted..
        /// </summary>
        public static string PrintResult_StatusNoCassette {
            get {
                return ResourceManager.GetString("PrintResult_StatusNoCassette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing failed for an unknown reason..
        /// </summary>
        public static string PrintResult_StatusUnknownFailure {
            get {
                return ResourceManager.GetString("PrintResult_StatusUnknownFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing failed with an unrecognized status code ({0})..
        /// </summary>
        public static string PrintResult_StatusUnrecognized {
            get {
                return ResourceManager.GetString("PrintResult_StatusUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The printer didn&apos;t report a result within the timeout - the label may or may not have printed..
        /// </summary>
        public static string PrintResult_Timeout {
            get {
                return ResourceManager.GetString("PrintResult_Timeout", resourceCulture);
            }
        }
    }
}
